name: Build and Release

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      BUNDLE: coraza-waf-proxy
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21

    - name: Build
      run: |
        go version
        go mod tidy
        go build -v -o ${{ env.BUNDLE }}
        chmod +x ${{ env.BUNDLE }}

    - name: Pack assets
      run: |
        mkdir ${{ env.BUNDLE }}
        cp ${{ env.BUNDLE }} LICENSE README.md ${{ env.BUNDLE }}/ || true
        tar cJf ${{ env.BUNDLE }}.tar.xz ${{ env.BUNDLE }}
        openssl sha256 ./${{ env.BUNDLE }} > sha256sum.txt
        echo "SHA256SUM=$(cut -d' ' -f2 sha256sum.txt)" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BUNDLE }}
        path: |
          ${{ env.BUNDLE }}
          ${{ env.BUNDLE }}.tar.xz
          sha256sum.txt

    - name: Upload release assets
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${GITHUB_REF##*/}" ${{ env.BUNDLE }} ${{ env.BUNDLE }}.tar.xz sha256sum.txt --clobber
