name: Build and Release

on:
  push:
    branches: [main]
    paths-ignore: [README.md]
  release:
    types: [published]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      BUNDLE: coraza-waf-proxy
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21

    - name: Build
      run: |
        go build -v -o ${{ env.BUNDLE }}
        chmod +x ${{ env.BUNDLE }}

    - name: Pack assets
      run: |
        mkdir release
        cp ${{ env.BUNDLE }} LICENSE README.md release/
        tar cJf ${{ env.BUNDLE }}.tar.xz release
        openssl sha256 ./${{ env.BUNDLE }} > sha256sum.txt
        echo "SHA256SUM=$(cut -d' ' -f2 sha256sum.txt)" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BUNDLE }}.tar.xz
        path: |
          ${{ env.BUNDLE }}.tar.xz
          sha256sum.txt

    - name: Upload release assets
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${GITHUB_REF##*/}" ${{ env.BUNDLE }}.tar.xz sha256sum.txt --clobber
