name: Build and Release

on:
  push:
    branches: [main, master]
    paths-ignore: [README.md]
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      BUNDLE: coraza-waf-proxy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21

    - name: Build
      run: |
        go version
        go mod init github.com/${{ github.repository }}
        go mod tidy
        go build -v -o ${{ env.BUNDLE }}

    - name: Pack assets
      run: |
        mkdir ${{ env.BUNDLE }}
        cp ${{ env.BUNDLE }} LICENSE README.md ${{ env.BUNDLE }}/
        tar cJf ${{ env.BUNDLE }}.tar.xz ${{ env.BUNDLE }}
        openssl sha256 ./${{ env.BUNDLE }} >sha256sum.txt
        echo "SHA256SUM=$(cut -d' ' -f2 sha256sum.txt)" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BUNDLE }}.tar.xz ${{ env.BUNDLE }} executable sha256 ${{ env.SHA256SUM }}
        path: |
          ${{ env.BUNDLE }}.tar.xz
          ${{ env.BUNDLE }}
          sha256sum.txt

    - name: Upload release assets
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${GITHUB_REF##*/}" ${{ env.BUNDLE }}.tar.xz ${{ env.BUNDLE }} sha256sum.txt --clobber
