name: Build and Release

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      BUNDLE: coraza-waf-proxy
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug info
      run: |
        echo "GitHub ref: ${{ github.ref }}"
        echo "GitHub event name: ${{ github.event_name }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "GitHub workflow: ${{ github.workflow }}"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21

    - name: Initialize Go module
      run: |
        go mod init github.com/${{ github.repository }}
        go mod tidy

    - name: Build
      run: |
        go version
        go env
        go build -v -o ${{ env.BUNDLE }}
        chmod +x ${{ env.BUNDLE }}

    - name: Pack assets
      run: |
        mkdir release
        cp ${{ env.BUNDLE }} LICENSE README.md release/ || true
        tar cJf ${{ env.BUNDLE }}.tar.xz release
        openssl sha256 ./${{ env.BUNDLE }} > sha256sum.txt
        echo "SHA256SUM=$(cut -d' ' -f2 sha256sum.txt)" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BUNDLE }}.tar.xz
        path: |
          ${{ env.BUNDLE }}.tar.xz
          sha256sum.txt

    - name: Upload release assets
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${GITHUB_REF##*/}" ${{ env.BUNDLE }}.tar.xz sha256sum.txt --clobber
